name: specta_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  dio: ^5.9.2
  flutter_secure_storage: ^10.3.1
  provider: ^6.1.5+1
  mobile_scanner: ^7.2.0
  google_fonts: ^8.1.0
  lucide_icons: ^0.257.0
  firebase_core: ^3.8.1
  firebase_messaging: ^15.1.6
  flutter_local_notifications: ^17.0.0
  audioplayers: ^6.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.2

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/specta.png"
  min_sdk_android: 24
flutter:
  uses-material-design: true
  assets:
    - assets/sounds/
    - .env
